# Generated by Django 4.1.1 on 2022-09-17 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nss', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngo',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
    ]
