# Generated by Django 4.1.1 on 2022-09-18 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nss', '0002_alter_ngo_phone_number_alter_student_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
