# Generated by Django 4.1.1 on 2022-09-19 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nss', '0004_remove_user_is_email_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngo',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
