# Generated by Django 4.1.1 on 2022-09-24 11:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nss', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Activity Name')),
                ('event_date', models.DateTimeField(verbose_name='Activity Date')),
                ('venue', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='nss.ngo')),
            ],
        ),
        migrations.CreateModel(
            name='Activity_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendence', models.CharField(choices=[('P', 'Present'), ('A', 'Absent')], default='P', max_length=1, verbose_name=models.ManyToManyField(blank=True, to='nss.student'))),
                ('marks', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name=models.ManyToManyField(blank=True, to='nss.student'))),
                ('activity_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.activity')),
                ('attendees', models.ManyToManyField(blank=True, to='nss.student')),
            ],
        ),
    ]
